[functions]
  directory = "funciones"
[build]
  functions = "netlify/functions"
  publish = "."

[[redirects]]
  from = "/guardar-clubes"
  to = "/.netlify/functions/guardar-clubes"
  status = 200
